token: "cloudflare token" # the cloudflare api token
timeout: "30s"            # how often do you want to check for ip updates?
zones:                    # define the zone/zones you wish to cover
  - example.com:
      v4-records:         # records of type A (leave empty or omit for none)
        - example.com:    # full record name (subdomain + zone name)
        - v6.example.com: # do not forget to add the " : " at the end of the declaration
      v6-records:         # records of type A (leave empty or omit for none)
        - v6.example.com:
loglevel: "error"         # if you want more info about what the program is doing, change it to "info"