token: "cloudflare token" # the cloudflare api token
timeout: "30s"            # how often do you want to check for ip updates?
zones: # define the zone/zones you wish to cover
  - example.com:
      v4-records: # records of type A (leave empty or omit for none)
        - example.com:    # full record name (subdomain + zone name)
        - v6.example.com: # do not forget to add the " : " at the end of the declaration
loglevel: "error"         # if you want more info about what the program is doing, change it to "info"

# DuckDNS specific
dd_domain:
dd_token:

# Endpoint for the JSON file with the IP. You might need to only change the IP of the router
endpoint: http://192.168.1.1/data/user_lang.json